---

- name: Create Nextcloud root directory
  file:
    path: "{{ nextcloud_path }}"
    state: directory
    owner: root
    group: "{{ nextcloud_user }}"
    mode: 0750

- name: Download and and extract Nextcloud {{ nextcloud_version }}
  unarchive:
    src: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"
    remote_src: yes
    dest: "{{ nextcloud_path }}/"
    owner: root
    group: "{{ nextcloud_user }}"
    mode: u=rwX,g=rX,o-rwx
    extra_opts:
    - --strip-components=1

- name: Setting strict permissions
  include_tasks: strict-permissions.yml

- name: Check if local database server is installed
  stat:
    path: /etc/mysql/my.cnf
  register: localdb

- name: Install Nextcloud on remote database server
  command: |
    sudo -u {{ nextcloud_user }} -- sh -c \
    'umask 0027; \
    php occ maintenance:install \
    --database "mysql" \
    --database-name "{{ nextcloud_db_name }}" \
    --database-host "{{ nextcloud_db_host }}" \
    --database-user "{{ nextcloud_db_user }}" \
    --database-pass "{{ nextcloud_db_password }}" \
    --admin-user "{{ nextcloud_admin }}" \
    --admin-pass "{{ nextcloud_admin_password }}" \
    --data-dir "{% if nextcloud_data_folder is not defined %}{{ nextcloud_path }}/data{% else %}{{ nextcloud_data_folder }}{% endif %}"'
  args:
    chdir: "{{ nextcloud_path }}"
  register: nextcloud_occ_install
  when: not localdb.stat.exists

- name: Install Nextcloud on local database server
  command: |
    sudo -u {{ nextcloud_user }} -- sh -c \
    'umask 0027; \
    php occ maintenance:install \
    --database "mysql" \
    --database-name "{{ nextcloud_db_name }}" \
    --database-user "{{ nextcloud_db_user }}" \
    --database-pass "{{ nextcloud_db_password }}" \
    --admin-user "{{ nextcloud_admin }}" \
    --admin-pass "{{ nextcloud_admin_password }}" \
    --data-dir "{% if nextcloud_data_folder is not defined %}{{ nextcloud_path }}/data{% else %}{{ nextcloud_data_folder }}{% endif %}"'
  args:
    chdir: "{{ nextcloud_path }}"
  register: nextcloud_occ_install
  when: localdb.stat.exists

- debug:
    msg: "{{ nextcloud_occ_install.stdout }}"
