---

- name: create nextcloud php pool service user
  user:
    state: present
    name: "{{ nextcloud_user }}"
    shell: /bin/false
    system: yes
    create_home: no
    home: /nonexistant/home
    comment: nextcloud php service user,,,

- name: check if Nextcloud is already installed
  stat:
    path: "{{ nextcloud_path }}/config/config.php"
  register: nextcloud_install

- name: determine currently installed version
  shell: |
    grep OC_VersionString {{ nextcloud_path }}/version.php | cut -d "'" -f2
  changed_when: false
  register: nextcloud_installed_version
  when: nextcloud_install.stat.exists

- name: New Nextcloud installation
  include_tasks: install.yml
  when: not nextcloud_install.stat.exists

- name: Nextcloud upgrade install
  include_tasks: upgrade.yml
  when: nextcloud_install.stat.exists and nextcloud_version is version(nextcloud_installed_version, '>')

- name: Setting Nextcloud config settings in config.php
  include_tasks: nextcloud-config.yml
  loop: "{{ nextcloud_config_settings }}"

