---

- name: create nextcloud php pool service user
  user:
    state: present
    name: "{{ nextcloud_user }}"
    shell: /bin/false
    system: yes
    create_home: no
    home: /nonexistant/home
    comment: nextcloud php service user,,,

- name: check if Nextcloud is already installed
  stat:
    path: "{{ nextcloud_path }}/config/config.php"
  register: nextcloud_install

- name: New Nextcloud installation
  include_tasks: install.yml
  when: not nextcloud_install.stat.exists

- name: Nextcloud upgrade install
  include_tasks: upgrade.yml
  when: nextcloud_install.stat.exists
- name: Setting Nextcloud config settings in config.php
  block:
    - name: Check current setting for {{ item.name }}
      shell: |
        sudo -u {{ nextcloud_user }} -- sh -c \
        'umask 0027; php occ config:system:get {{ item.name }} --value="{{ item.value }}"'
      args:
        chdir:
      register: config_setting
      changed_when: false

    - name: Setting {{ item.name }} to {{ item.value }}
      shell: |
        sudo -u {{ nextcloud_user }} -- sh -c \
        'umask 0027; php occ config:system:set {{ item.name }} --value="{{ item.value }}"'
      args:
        chdir: "{{ nextcloud_path }}"
      when: config_setting.stdout != item.value
  loop: "{{ nextcloud_config_settings }}"
  
- name: Setting strict permissions
  include_tasks: strict-permissions.yml
