---

- name: Check current setting for {{ item.name }}
  shell: |
    sudo -u {{ nextcloud_user }} -- sh -c \
    'umask 0027; php occ config:system:get {{ item.name }}'
  args:
    chdir: "{{ nextcloud_path }}"
  register: config_setting
  failed_when: config_setting.rc == 1 and (config_setting.stdout is defined or config_setting.stderr is defined)
  changed_when: false

- name: Setting {{ item.name }} to {{ item.value }}
  shell: |
    sudo -u {{ nextcloud_user }} -- sh -c \
    'umask 0027; php occ config:system:set {{ item.name }} --value="{{ item.value }}"'
  args:
    chdir: "{{ nextcloud_path }}"
  when: config_setting.stdout != item.value
