---

- name: set strict permissions
  block:
    - file:
        path: "{{ nextcloud_path }}/{{ item }}"
        state: directory
      loop:
        - data
        - assets
        - updater
    - file:
        path: "{{ nextcloud_path }}"
        owner: root
        group: "{{ nextcloud_user }}"
        mode: u=rwX,g=rX
        recurse: yes
    - file:
        path: "{{ nextcloud_user }}/{{ item }}"
        owner: "{{ nextcloud_user }}"
        group: "{{ nextcloud_user }}"
      loop:
        - apps
        - assets
        - config
        - data
        - themes
        - updater
    - file:
        path: "{{ nextcloud_user }}/occ"
        mode: '+x'
